ui:
  service:
    type: "null"

connectInject:
  enabled: true

client:
  enabled: true
  grpc: true

server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  storage: 10Gi
  storageClass: nfs
  connect: true
